"""
Cross-engine parity tests: Python engine vs TypeScript engine.

Fixtures are generated by the TS engine via:
    npm run gen-fixtures   (in Canister.HexWar/)

Each fixture captures a deterministic game run with zero player orders
(no moves issued), which exercises unit generation and win/elimination
detection in isolation from any AI divergence. The Python engine replays
the same turns on the same initial board and must produce identical results.

Fixture discovery: looks for *.json files in the directory pointed to by
HEXWAR_FIXTURES_DIR env var, or the default relative path below.
"""

import copy
import json
import os
from pathlib import Path

import pytest

from hexwar.engine.turn_resolver import resolve_player_turn
from hexwar.engine.types import AxialCoord, Player, PlayerStats, PlayerType, Tile
from hexwar.engine.unit_generator import generate_units

# ---------------------------------------------------------------------------
# Fixture path
# ---------------------------------------------------------------------------

_DEFAULT_FIXTURES = Path(__file__).parent.parent.parent / "packages" / "engine" / "fixtures"
FIXTURES_DIR = Path(os.environ.get("HEXWAR_FIXTURES_DIR", _DEFAULT_FIXTURES))


# ---------------------------------------------------------------------------
# Deserialisation helpers
# ---------------------------------------------------------------------------

def _load_board(raw: dict) -> dict:
    """Convert a serialised TS board (camelCase) into a Python Board dict."""
    board = {}
    for key, t in raw.items():
        coord = AxialCoord(q=t["coord"]["q"], r=t["coord"]["r"])
        board[key] = Tile(
            coord=coord,
            owner=t["owner"],
            units=t["units"],
            is_start_tile=t["isStartTile"],
            start_owner=t["startOwner"],
            terrain=t["terrain"],
            newly_conquered=t["newlyConquered"],
        )
    return board


def _make_players(player_ids: list[str]) -> list[Player]:
    return [
        Player(id=pid, name=pid, color="#000000", type=PlayerType.AI)
        for pid in player_ids
    ]


def _make_stats(player_ids: list[str]) -> dict[str, PlayerStats]:
    return {
        pid: PlayerStats(
            player_id=pid,
            tiles_held=0,
            units_generated=0,
            units_lost=0,
            units_killed=0,
            tiles_captured=0,
            tiles_lost=0,
        )
        for pid in player_ids
    }


def _boards_equal(py_board: dict, ts_board: dict, label: str) -> list[str]:
    """Return list of mismatch descriptions, empty if equal."""
    mismatches = []
    all_keys = set(py_board) | set(ts_board)
    for key in sorted(all_keys):
        if key not in py_board:
            mismatches.append(f"{label} key {key!r} missing in Python board")
            continue
        if key not in ts_board:
            mismatches.append(f"{label} key {key!r} missing in TS board")
            continue
        py = py_board[key]
        ts = ts_board[key]
        if py.owner != ts["owner"]:
            mismatches.append(f"{label} {key}: owner py={py.owner!r} ts={ts['owner']!r}")
        if py.units != ts["units"]:
            mismatches.append(f"{label} {key}: units py={py.units} ts={ts['units']}")
        if py.newly_conquered != ts["newlyConquered"]:
            mismatches.append(f"{label} {key}: newly_conquered py={py.newly_conquered} ts={ts['newlyConquered']}")
    return mismatches


# ---------------------------------------------------------------------------
# Parametrize over fixtures
# ---------------------------------------------------------------------------

def _fixture_files() -> list[Path]:
    if not FIXTURES_DIR.exists():
        return []
    return sorted(FIXTURES_DIR.glob("fixture_seed_*.json"))


@pytest.fixture(params=_fixture_files(), ids=lambda p: p.stem)
def fixture_data(request):
    with open(request.param) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_fixture_dir_exists():
    """Fail clearly if fixtures haven't been generated yet."""
    if not FIXTURES_DIR.exists():
        pytest.skip(
            f"Fixtures not found at {FIXTURES_DIR}. "
            "Run 'npm run gen-fixtures' in Canister.HexWar/ to generate them."
        )
    files = list(FIXTURES_DIR.glob("fixture_seed_*.json"))
    assert len(files) > 0, f"No fixture files in {FIXTURES_DIR}"


def test_unit_generation_parity(fixture_data):
    """
    Python engine must produce the same board as TS after each turn of
    zero-order play (only unit generation runs).
    """
    player_ids: list[str] = fixture_data["playerIds"]
    board = _load_board(fixture_data["initialBoard"])
    players = _make_players(player_ids)
    stats = _make_stats(player_ids)

    for turn_data in fixture_data["turns"]:
        turn_num = turn_data["turn"]

        # Replay each player's zero-order turn
        for snap in turn_data["playerSnapshots"]:
            pid = snap["playerId"]
            player = next((p for p in players if p.id == pid), None)
            if player is None or player.is_eliminated:
                continue

            result = resolve_player_turn(board, players, {}, pid, copy.deepcopy(stats))
            board = result.board
            players = result.players
            # Merge stats updates
            for k, v in result.stats.items():
                stats[k] = v

            # Compare with TS snapshot (skip empty snapshots for eliminated players)
            ts_board_after = snap["boardAfter"]
            if not ts_board_after:
                continue
            mismatches = _boards_equal(board, ts_board_after, f"turn {turn_num} after {pid}")
            assert not mismatches, "\n".join(mismatches[:10])

        # Unit generation
        ts_board_after_gen = turn_data.get("boardAfterUnitGen")
        if ts_board_after_gen is None:
            break  # game ended before unit gen this turn

        generate_units(board, stats)  # mutates in place
        mismatches = _boards_equal(board, ts_board_after_gen, f"turn {turn_num} after unit gen")
        assert not mismatches, "\n".join(mismatches[:10])
